return {
	misc = {
		dictionary = {
			k_multiplayer = 'Multiplayer',
			k_status_offline = 'Offline',
			k_status_connecting = 'Connecting...',
			k_status_signing_in = 'Signing In...',
			k_status_connected = 'Connected',
			k_status_queueing = 'Queueing',
			k_your_avatar_cap_1 = 'YOUR',
			k_your_avatar_cap_2 = 'AVATAR',
			k_click_to_change = 'Click to Change',
			k_dev_mode_suffix = '(Dev)',
			k_not_linked = 'Not Linked',
			k_multiplayer_account = 'Multiplayer Account',
			k_id = 'ID',
			k_steam_username = 'Steam Username',
			k_discord_username = 'Discord Username',
			k_display_name = 'Display Name',
			k_auto_login = 'Auto Login',
			k_steam = 'Steam',
			k_discord = 'Discord',
			k_link_discord = 'Link Discord',
			k_unlink_discord = 'Unlink Discord',
			k_tos_title = 'Before You Play',
			k_tos_first_time_1 = 'A couple of things to sort out first.',
			k_tos_update_1 = 'The Privacy & Terms Notice has been updated.',
			k_tos_update_2 = 'Please review and accept to continue.',
			k_tos_blocked_title = 'Account creation is unavailable.',
			k_tos_birth_section = 'Your birthday',
			k_tos_birth_hint = "We won't store it, we just need to check that you are old enough to play.",
			k_tos_agreement_section = 'What you\'re agreeing to',
			k_tos_bullet_1 = 'We save your Steam display name, hashed identifiers, and match results.',
			k_tos_bullet_2 = "We don't sell your data or use it for ads. Ever.",
			k_tos_bullet_3 = 'You can delete your account from the account overlay at any time.',
			k_tos_agree = 'I have read and agree to the Privacy & Terms Notice',
			b_open_download_page = 'Open Download Page',
			b_coming_soon = 'Coming Soon',
			b_retry_connection = 'Retry Connection',
			b_log_in = 'Log In',
			b_view_notice = 'View Privacy & Terms Notice',
			b_create_account = 'Create Account',
			b_sign_up = 'Sign Up',
			b_sign_in = 'Sign In',
			b_i_accept = 'I Accept',
			b_i_decline = 'I Decline',
			k_you = 'You',
			k_chat_not_enabled = '[MultiplayerAPI] Chat is not enabled. You can enable it in the account overlay on the main menu.',
			k_chat_lobby_only = '[MultiplayerAPI] Chat is only available while in a lobby.',
			k_chat_dp_compat_info = '[MultiplayerAPI] For compatibility with DebugPlus, all DebugPlus commands must be prefixed with /. Anything sent without a / will be sent as a chat message.',
			k_chat_ready_dp = '[MultiplayerAPI] Chat ready. Open console with / or T',
			k_chat_ready = '[MultiplayerAPI] Chat ready. Press T to open',
			k_chat_unknown_command = 'Unknown command',
			-- Chat section in account overlay
			k_chat_section_title = 'Chat',
			k_chat_status_enabled = 'Chat is enabled',
			k_chat_status_blocked = 'Chat access is permanently restricted',
			k_chat_status_none = 'Chat is not set up',
			b_chat_enable = 'Enable Chat',
			-- Chat enable overlay (birthdate picker)
			k_chat_enable_title = 'Enable Chat',
			k_chat_enable_desc = 'Once enabled, you can send and receive messages in lobbies.',
			k_chat_birth_month = 'Month',
			k_chat_birth_day = 'Day',
			k_chat_birth_year = 'Year',
			k_chat_birth_privacy_1 = 'We do not store your date of birth anywhere.',
			k_chat_birth_privacy_2 = 'It is collected solely to enable chat on your account, as required by child safety regulations in many countries.',
			b_chat_submit_age = 'Confirm',
			-- Queue guard overlay (blocks starting a run while queued)
			k_queue_guard_title = 'Matchmaking In Progress',
			k_queue_guard_desc = "You can't start a run or join a lobby while searching for a match.",
			b_queue_guard_leave_play = 'Leave Queue & Continue',
			b_queue_guard_leave = 'Leave Queue',
			b_queue_guard_stay = 'Stay Queued',
			-- In-game chat feedback
			k_chat_age_blocked = '[MultiplayerAPI] Chat is not available for your account.',
			k_chat_client_disabled = '[MultiplayerAPI] Chat is disabled. Re-enable it in the account overlay.',
			k_join_lobby_cap = 'JOIN LOBBY',
			k_lobby_code_cap = 'LOBBY CODE',
			k_copied_cap = 'COPIED!',
			b_create_lobby_cap = { 'CREATE', 'LOBBY' },
			b_by_code_cap = 'BY CODE',
			b_from_clipboard_cap = 'FROM CLIPBOARD',
			b_view_code_cap = 'VIEW CODE',
			b_copy_code_cap = 'COPY CODE',
			b_find_game_cap = 'FIND GAME',
			b_open_lobby_cap = { 'OPEN', 'LOBBY' },
			b_lobby_options_cap = { 'LOBBY', 'OPTIONS' },
			b_leave_lobby_cap = { 'LEAVE', 'LOBBY' },
			b_start_game_cap = { 'START', 'GAME' },
			-- Shared matchmaking / lobby menu strings (used by all consumer mods, e.g.
			-- Speedrunning and PvP), kept here so consumers don't each duplicate them.
			b_leaderboard_cap = 'LEADERBOARD',
			b_practice_cap = 'PRACTICE',
			b_searching_cap = 'SEARCHING...',
			b_cancel_search_cap = 'CANCEL',
			b_ready_cap = 'READY',
			b_unready_cap = 'UNREADY',
			k_ranked_cap = 'RANKED',
			k_casual_cap = 'CASUAL',
			k_rating_cap = 'RATING',
			k_best_score_cap = 'BEST',
			k_waiting_for_players = 'Waiting for players...',
			-- Deck ban-pick draft
			k_banpick_title = 'DECK BAN',
			k_banpick_waiting = 'Selecting decks...',
			k_banpick_your_turn = 'Your turn: ban a deck',
			k_banpick_their_turn = 'Waiting for opponent...',
			k_banpick_bans_left = 'Bans left:',
			k_banpick_decks_left = 'Decks left:',
			k_banpick_ban = 'Ban',
			k_banpick_pick = 'Pick',
			k_banpick_pick_turn = 'Your turn: pick your deck',
			k_banpick_banned = 'BANNED',
			k_banpick_selected = 'Selected:',
			k_banpick_selected_tag = 'Selected',
			k_banpick_confirm = 'Confirm Ban',
			k_banpick_confirm_pick = 'Confirm Pick',
			k_banpick_confirm_random = 'Confirm Random',
			k_banpick_random = 'Random',
			k_banpick_cancel_random = 'Cancel Random',
			k_banpick_weekly_mix = 'A rotating 3-deck mix',
			k_cocktail_suffix = 'Cocktail',
		},
	},
	descriptions = {
		Other = {
			-- ── Skip Tags ─────────────────────────────────
			to_p1t1 = {
				name = 'Uncommon Tag',
				text = {
					'{C:attention}Uncommon Tags{} work similarly to {C:attention}Rare Tags{}. There is a game',
					'long Uncommon Joker {C:chips}queue{} seperate from the {C:chips}shop queue{}. This',
					'means {C:attention}Uncommon Tags{} are the only way to advance this {C:chips}queue{}.',
					'You will sometimes see players taking Uncommon skips for',
					'extra variance, as it is an extra chance for an {C:attention}Idol{}, {C:attention}Dusk{},',
					'or {C:attention}Mime{} that your nemesis will {C:red}never{} see. (unless they take',
					'an {C:attention}Uncommon Tag{})',
					' ',
				},
			},
			to_p1t2 = {
				name = 'Voucher Tag',
				text = {
					'{C:attention}Voucher tags{} advance the {C:chips}Voucher queue{}. They do this in the',
					'same manner that seeing another ante does. For a more in',
					'depth explanation with examples see the {C:chips}Shop Queue{} tab',
					' ',
				},
			},
			to_p1t3 = {
				name = 'Riff-raff / Top Up',
				text = {
					'Both {C:attention}Riff-Raff{} and {C:attention}Top Up Tag{} take from the same {C:chips}queue{}. They',
					'do {C:red}NOT{} take from the {C:chips}shop queue{}. This means that these can',
					'provide Common Jokers your nemesis will {C:red}never{} see',
					' ',
				},
			},
			to_p1t4 = { name = 'Orbital Tag', text = {
				'Only change is standardization between {C:attention}Mac{} and {C:attention}Windows{}. Can',
				'still desync if players have different hands unlocked',
				' ',
			} },
			to_p1t5 = {
				name = 'Rare Tag / Wraith',
				text = {
					'{C:attention}Rare Tags{} share a {C:chips}game long queue{} with {C:spectral}Wraith{}. This {C:chips}queue{}',
					'does {C:red}NOT{} take from the shop, but rather is a completely',
					'seperate {C:chips}queue{}. The only way to advance this {C:chips}queue{} is by',
					'taking Rare skips or {C:spectral}Wraiths{}',
					' ',
				},
			},
			-- ── Consumables ───────────────────────────────
			to_p2t1 = { name = 'Aura', text = {
				'{C:spectral}Aura{} works on a {C:chips}game long queue{}. This is how {C:spectral}Aura{} works in',
				'Vanilla',
				' ',
			} },
			to_p2t2 = {
				name = 'Rare Tag / Wraith',
				text = {
					'{C:spectral}Wraith{} shares a {C:chips}game long queue{} with Rare Skips. This {C:chips}queue{}',
					'does {C:red}NOT{} take from the shop, but rather is a completely',
					'seperate {C:chips}queue{}. The only way to advance this {C:chips}queue{} is by',
					'taking Rare skips or {C:spectral}Wraiths{}',
					' ',
				},
			},
			to_p2t3 = {
				name = 'Judgement',
				text = {
					'{C:tarot}Judgement{} takes Jokers from its own seperate {C:chips}queue{} on Orange',
					'{C:attention}Stake+{}. On other stakes, it takes the next Joker from the',
					'{C:chips}shop queue{}',
					' ',
				},
			},
			-- ── Card Modifiers ────────────────────────────
			to_p3t1 = {
				name = 'Glass',
				text = {
					'Despite {C:tarot}Justice{} being {C:red}banned{}, Glass is still avalable in',
					'Standard Packs and via the {C:spectral}Familiar{}, {C:spectral}Grim{}, and {C:spectral}Incantation{}',
					'Spectral cards. Glass however, has been changed to give',
					'{C:mult}1.5x mult{} on trigger, rather than the {C:mult}Vanilla 2x{}.',
					'Additionally, Glass breaks work on a {C:chips}game long queue{}.',
					' ',
				},
			},
			to_p3t2 = {
				name = 'Lucky',
				text = {
					'Lucky cards work on 2 game long {C:chips}queues{}. One for the {C:green}1/5{}',
					'chance to hit mult. One for the {C:green}1/15{} chance for {C:money}$20{}. This is',
					'the same way Lucky cards work in Vanilla',
					' ',
				},
			},
			to_p3t3 = { name = 'Purple Seal', text = {
				'{C:attention}Purple Seals{} take from the {C:chips}Up Top Tarot Queue{}',
				' ',
			} },
			-- ── Decks ─────────────────────────────────────
			to_p4t1 = {
				name = 'Orange Deck',
				text = {
					'Multiplayer Exclusive. Start run with a {C:attention}Giga Standard Pack{}',
					'(Read more about this in the Packs tab). Start run with 2',
					'copies of Hanged Man',
					' ',
				},
			},
			to_p4t2 = { name = 'Purple Deck', text = {
				'Multiplayer Exclusive. 1 additional Voucher Slot. During',
				'{C:attention}Ante 1{}, Vouchers are {C:money}50% off{}',
				' ',
			} },
			-- ── Jokers ────────────────────────────────────
			to_p5t1 = { name = 'Superposition +', text = {
				'These 3 Vanilla Jokers work as expected, with the Tarot',
				'cards they give taken from the {C:chips}Up Top Tarot Queue{}',
				' ',
			} },
			to_p5t2 = {
				name = 'Prob. Jokers',
				text = {
					'The 6 Vanilla Jokers to the left work basically as expected,',
					'operating on one {C:chips}game long queue{} that progresses every time',
					'you trigger the Joker. {C:attention}8-Ball{} and {C:attention}Hallucination{} take from',
					'the {C:chips}Up Top Tarot Queue{}. {C:attention}Oops All 6s{} doubles the number that',
					'must be rolled less than',
					' ',
				},
			},
			to_p5t3 = {
				name = 'Golden Ticket',
				text = {
					'{C:attention}Golden ticket{} has been changed in a couple ways. It is now',
					'{C:attention}Uncommon Rarity{} instead of Common. It now gives {C:money}$3{} instead',
					'of {C:money}$4{}. No longer requires the player to have a gold card in',
					'the deck to appear in shop',
					' ',
				},
			},
			to_p5t4 = {
				name = 'Seance / Sixth Sense',
				text = {
					'{C:attention}Seance{} and {C:attention}Sixth Sense{} take the Spectral cards they generate',
					'from the {C:chips}Up Top Spectral Queue{}. {C:attention}Invisible Joker{}, Ancient',
					'Joker, Sock and Buskin, and Photograph work as expected',
					' ',
				},
			},
			to_p5t5 = {
				name = 'Riff-Raff / Top Up',
				text = {
					'Both {C:attention}Riff-Raff{} and {C:attention}Top Up Tag{} take from the same {C:chips}queue{}. They',
					'do {C:red}NOT{} take from the {C:chips}shop queue{}. This means that these can',
					'provide Common Jokers your nemesis will {C:red}never{} see',
					' ',
				},
			},
			to_p5t6 = {
				name = 'To Do List',
				text = {
					'{C:attention}To Do List{} is technically not changed from vanilla, besides',
					'making sure {C:attention}Mac{} and {C:attention}Windows{} users have the same {C:attention}To Do List{}',
					'{C:chips}queue{}',
					' ',
				},
			},
			to_p5t7 = {
				name = 'Invisible Joker',
				text = {
					'{C:attention}Invisible Joker{} has been changed to decrease the variance',
					'between players on what it hits. Previously both players',
					'could copy different joker positions independently. Now if',
					"both players share N jokers, player 2's extra joker is hit",
					'at only {C:green}1/N{} chance, with all others copying what both',
					'players share',
					' ',
				},
			},
			to_p5t8 = {
				name = 'Bloodstone',
				text = {
					'{C:attention}Bloodstone{} operates on 2 seperate {C:chips}queues{}. The first is game',
					'long and progresses every time you play a heart while {C:red}NOT{} in',
					'a Pvp blind. {C:attention}Bloodstone{} has a {C:chips}Pvp queue{} that changes each',
					'ante. While in Pvp, after playing a hand, {C:attention}Bloodstone{} returns',
					'to the beginning of the {C:chips}Pvp queue{}',
					' ',
				},
			},
			-- ── Misc ──────────────────────────────────────
			to_p6t1 = {
				name = 'Hand Smoothing',
				text = {
					'Not a really important change since this type of effect is',
					'so hard to measure. This changes the Ante based draws in',
					'Vanilla to be Round based instead. This essentially makes',
					'draws slightly more similar.',
					' ',
				},
			},
			-- ── Packs ─────────────────────────────────────
			to_p7t1 = {
				name = 'Arcana / Spectral',
				text = {
					'All Arcana, Celestial, and Spectral packs take from their',
					"respective consumable's {C:chips}Pack queue{}. See the {C:chips}Shop Queue{} tab",
					'for a more in depth explanation with examples',
					' ',
				},
			},
			to_p7t2 = { name = 'Buffoon Pack', text = {
				'Buffoon Packs take directly from the {C:chips}Shop Queue{}. Normal',
				'Packs take the next 2 Jokers. Jumbo and Mega take the next 4',
				'Jokers',
				' ',
			} },
			to_p7t3 = {
				name = 'Standard Pack',
				text = {
					'Standard Packs take from a game long Playing Card {C:chips}queue{}.',
					'This {C:chips}queue{} is seperate from the {C:attention}Magic Trick{} Playing Card',
					'{C:chips}queue{}. This does mean that if you open a Normal than a',
					'Jumbo, it is possible you end up with 2 cards you want in',
					'the Jumbo and none in the Normal, whereas you would have',
					'been able to take both if you opened them in the other order',
					' ',
				},
			},
			-- ── Shop Queue ────────────────────────────────
			to_p8t1 = {
				name = 'Overview',
				text = {
					'The {C:chips}shop queue{} in Balatro Multiplayer differs from Vanilla',
					'in many ways. There are 3 sections of the Shop, each with',
					'their own {C:chips}queues{}: the Main shop, the Pack shop, and the',
					'Voucher shop. Skipping does {C:red}NOT{} advance the {C:chips}queue{} for your',
					'nemesis',
					' ',
				},
			},
			to_p8t2 = {
				name = 'Sub-Queues',
				text = {
					'The {C:chips}Main Shop Queue{} is seperated into 7 sub {C:chips}queues{}. Common',
					'Joker Queue. {C:chips}Uncommon Joker Queue{}. {C:chips}Rare Joker Queue{}. Up Top',
					'Tarot Queue. {C:chips}Up Top Planet Queue{}. {C:chips}Up Top Spectral Queue{}.',
					'{C:chips}Playing Card Queue{}. Every time you see a new Shop or Reroll,',
					'you progress the {C:chips}Main Shop Queue{}',
					' ',
				},
			},
			to_p8t3 = {
				name = 'How It Works',
				text = {
					'If {C:attention}Player 1{} skips and {C:attention}Player 2{} does not, {C:attention}Player 1{} will still',
					'see the packs that {C:attention}Player 2{} does, just a blind after.',
					'Rerolling only advances the {C:chips}queue{} for that player',
					' ',
				},
			},
			-- ── Vouchers ──────────────────────────────────
			to_p9t1 = {
				name = 'Vouchers',
				text = {
					'No vouchers are changed from Vanilla itself. However, read',
					'more about the changes to the {C:chips}Voucher queue{} (when vouchers',
					'come up in shop) in the {C:chips}Shop Queue{} tab',
					' ',
				},
			},
		},
	},
}
